config/routes.rb
Rails.application.routes.draw do
  root to: 'vue_application#index'
  # get '/*path', to: 'vue_application#index'

  resources :about, only: :index, to: 'vue_application#index'
  resources :gallery, only: %i[index], to: 'vue_application#index'
  resources :works, only: %i[index show], to: 'vue_application#index'
  resources :books, only: %i[index], to: 'vue_application#index'
  resources :contact, only: :index, to: 'vue_application#index'
  resources :policy, controller: :policy, only: :index, to: 'vue_application#index'

  namespace :api do
    resource :contact, controller: 'contact'
    resource :about, controller: 'about'
  end

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/about.rb
class About < ApplicationRecord
  belongs_to :ichikawa_satsuki, optional: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ichikawa_satsuki.rb
class IchikawaSatsuki < ApplicationRecord
  has_many :abouts, dependent: :destroy
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def show; end
end

app/controllers/api/about_controller.rb
module Api
  class AboutController < ApplicationApiController
    before_action :setup_about
    def show
      contents = {
        title: @about.title,
        sub_title: @about.sub_title,
        body: @about.body,
        image_url: @about.image_url,
        cv_title: "Happy Customers"
      }
      render json: contents, status: :ok
    end

    def update
      new_about = About.create!(
        ichikawa_satsuki: owner,
        title: about_params[:title],
        sub_title: about_params[:sub_title],
        body: about_params[:body],
        image_url: 'https://res.cloudinary.com/jo-test/image/upload/v1594141502/about2_qm5a4z.jpg'
      )
      contents = {
        title: new_about.title,
        sub_title: new_about.sub_title,
        body: new_about.body,
        image_url: 'https://res.cloudinary.com/jo-test/image/upload/v1594141502/about2_qm5a4z.jpg',
        cv_title: about_params[:cv_title]
      }
      render json: contents, status: :ok
    end

    private

    def setup_about
      @about = About.order(:id).last
    end

    def about_params
      params.require(:about).permit(:title, :sub_title, :body, :cv_title)
    end
  end
end

app/controllers/api/application_api_controller.rb
module Api
  class ApplicationApiController < ::ActionController::API
    protected

    def owner
      @owner ||= IchikawaSatsuki.order(:id).first
    end
  end
end

app/controllers/api/contact_controller.rb
module Api
  class ContactController < ApplicationApiController
    def create
      @contact = ContactForm.new(contact_params)
      if @contact.save
        render json: { message: I18n.t('views.common.sent_a_message') }, status: :ok
      else
        render json: { errors: @contact.errors.full_messages }, status: :unprocessable_entity
      end
    end

    private

    def contact_params
      params.require(:contact).permit(:name, :email, :date, :place, :message, :privacy_policy, shooting_types: [])
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

  def show; end

  # Ajax
  def create
    @contact = ContactForm.new(contact_params)
    if @contact.save
      render json: { message: I18n.t('views.common.sent_a_message') }, status: :ok
    else
      render json: { errors: @contact.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def connect
    render json: ContactForm.shooting_items, status: :ok
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :email, :date, :place, :message, :privacy_policy, shooting_items: [])
  end
end

app/controllers/gallery_controller.rb
class GalleryController < ApplicationController
  def index; end

  def show
    @category = params[:id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show; end
end

app/controllers/policy_controller.rb
class PolicyController < ApplicationController
  def show; end
end

app/controllers/vue_application_controller.rb
class VueApplicationController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/show.html.slim
.content-wrapper
  .wrapper.light-wrapper
    .container.inner.pt-60
      .boxed
        .bg-white.shadow.rounded
          .image-block-wrapper
            .image-block.col-lg-6
              .image-block-bg.bg-image data-image-src="/assets/art/about2.jpg"
            .container-fluid
              .row
                .col-lg-6.offset-lg-6
                  .box.d-flex
                    .align-self-center
                      h3.mb-20 I'm here to capture your moments
                      p.lead Hi! I’m Missio, a wedding photographer currently working and residing in London. I absolutely love shooting weddings because there are so many feelings to capture.
                      p Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Cras mattis consectetur purus sit amet fermentum. Nulla vitae elit libero, a pharetra augue. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Aenean lacinia bibendum nulla sed consectetur. Cum sociis natoque penatibus.
                      ul.social.social-color
                        li
                          a href="javascript:void(0)"
                            i.fa.fa-twitter
                        li
                          a href="javascript:void(0)"
                            i.fa.fa-facebook
                        li
                          a href="javascript:void(0)"
                            i.fa.fa-flickr
                        li
                          a href="javascript:void(0)"
                            i.fa.fa-instagram
                        li
                          a href="javascript:void(0)"
                            i.fa.fa-pinterest-p
  .wrapper.light-wrapper
    .container.inner
      h2.section-title.text-center Happy Customers
      .cube-carousel.cbp
        .cbp-item
          .box.bg-white.shadow
            blockquote.icon.icon-left
              p Sed posuere consectetur est at lobortis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis mollis, est non commodo luctus, nisi erat porttitor ligula lacinia odio.
              footer.blockquote-footer Connor Gibson
        .cbp-item
          .box.bg-white.shadow
            blockquote.icon.icon-left
              p Sed posuere consectetur est at lobortis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis mollis, est non commodo luctus, nisi erat porttitor ligula lacinia odio.
              footer.blockquote-footer Coriss Ambady
        .cbp-item
          .box.bg-white.shadow
            blockquote.icon.icon-left
              p Sed posuere consectetur est at lobortis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis mollis, est non commodo luctus, nisi erat porttitor ligula lacinia odio.
              footer.blockquote-footer Barclay Widerski
        .cbp-item
          .box.bg-white.shadow
            blockquote.icon.icon-left
              p Sed posuere consectetur est at lobortis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis mollis, est non commodo luctus, nisi erat porttitor ligula lacinia odio.
              footer.blockquote-footer Nikola Brooten
        .cbp-item
          .box.bg-white.shadow
            blockquote.icon.icon-left
              p Sed posuere consectetur est at lobortis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis mollis, est non commodo luctus, nisi erat porttitor ligula lacinia odio.
              footer.blockquote-footer Jackie Sanders
        .cbp-item
          .box.bg-white.shadow
            blockquote.icon.icon-left
              p Sed posuere consectetur est at lobortis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis mollis, est non commodo luctus, nisi erat porttitor ligula lacinia odio.
              footer.blockquote-footer Cory Zamora
        .cbp-item
          .box.bg-white.shadow
            blockquote.icon.icon-left
              p Sed posuere consectetur est at lobortis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis mollis, est non commodo luctus, nisi erat porttitor ligula lacinia odio.
              footer.blockquote-footer Pierce Bailey
  .wrapper.gray-wrapper
    .container.inner
      h2.section-title.text-center Instagram Feed
      p.lead.text-center Here you will find the latest shots from our Instagram feed.
      .space20
      .tiles.tiles-s
        #instafeed.items.row
      .space40
      .text-center
        a.btn href="#" Instagram Page

app/views/common/_footer.html.slim
footer.dark-wrapper.inverse-text
  .container.inner
    .row.d-md-flex.align-items-md-center
      .col-md-4.text-center.text-md-left
        p.mb-0 © 2019 Missio. All rights reserved.
      .col-md-4.text-center
        img src="#" srcset="/assets/logo-light.png 1x, /assets/logo-light@2x.png 2x" alt=""
      .col-md-4.text-center.text-md-right
        ul.social.social-mute.social-s.mt-10
          li
            a href="javascript:void(0)"
              i.fa.fa-twitter
          li
            a href="javascript:void(0)"
              i.fa.fa-facebook-f
          li
            a href="javascript:void(0)"
              i.fa.fa-pinterest
          li
            a href="javascript:void(0)"
              i.fa.fa-vimeo
          li
            a href="javascript:void(0)"
              i.fa.fa-instagram

app/views/common/_header.html.slim
nav.navbar.center.navbar-expand-lg
  .container.flex-lg-column
    .navbar-header
      .navbar-brand
        = link_to root_path do
          img src="#" srcset="/assets/logo.png 1x, /assets/logo@2x.png 2x" alt=""
      .navbar-hamburger.ml-auto.d-lg-none.d-xl-none
        button.hamburger.animate data-toggle="collapse" data-target=".navbar-collapse"
    .navbar-collapse.collapse.w-100.bg-light
      ul.navbar-nav.nav-fill.w-100
        li.nav-item
          = link_to t('.menu.home'), root_path, class: 'nav-link'
        li.nav-item
          = link_to t('.menu.about'), about_path, class: 'nav-link'
        li.nav-item
          = link_to t('.menu.gallery'), gallery_index_path, class: 'nav-link'
        li.nav-item
          = link_to 'WORKS', 'javascript:void(0)', class: 'nav-link'
        li.nav-item
          = link_to t('.menu.blog'), 'http://blog.ichikawasatsuki.com', class: 'nav-link', target: '_blank'
        li.nav-item
          = link_to t('.menu.contact'), contact_path, class: 'nav-link'

app/views/common/_home_header.html.slim
nav.navbar.wide.transparent.transparent-light.absolute.navbar-expand-lg
  .container-fluid.flex-row.justify-content-center
    .navbar-header
      .navbar-brand
        a href="index.html"
          img src="#" srcset="/assets/logo2.png 1x, /assets/logo2@2x.png 2x" alt=""
      .navbar-hamburger.ml-auto.d-lg-none.d-xl-none
        button.hamburger.animate data-toggle="collapse" data-target=".navbar-collapse"

    .navbar-collapse.collapse.justify-content-between.align-items-center
      ul.navbar-nav.plain.mx-auto.text-center
        li.nav-item
          = link_to t('.menu.home'), root_path, class: 'nav-link'
        li.nav-item
          = link_to t('.menu.about'), about_path, class: 'nav-link'
        li.nav-item
          = link_to t('.menu.gallery'), gallery_index_path, class: 'nav-link'
        li.nav-item
          = link_to 'WORKS', 'javascript:void(0)', class: 'nav-link'
        li.nav-item
          = link_to t('.menu.blog'), 'http://blog.ichikawasatsuki.com', class: 'nav-link', target: '_blank'
        li.nav-item
          = link_to t('.menu.contact'), contact_path, class: 'nav-link'
    .social-wrapper.text-right
      ul.social.social-mute.social-s.mb-0
        li
          a href="javascript:void(0)"
            i.fa.fa-twitter
        li
          a href="javascript:void(0)"
            i.fa.fa-facebook-f
        li
          a href="javascript:void(0)"
            i.fa.fa-vimeo
        li
          a href="javascript:void(0)"
            i.fa.fa-instagram

app/views/contact/show.html.slim
- content_for :vue_template do
  = render 'components/contact/contact_component'

.wrapper.light-wrapper
  .container.inner.pt-70
    .row
      .col-lg-8.offset-lg-2
        h2.section-title.text-center
          = t '.title'
        p.text-center
          = t '.description'
        .space20
        #contact
          contact-component[
            ajax-path="#{contact_path}"
            get-data-ajax-path="#{connect_contact_path}"
            btn-default-msg="#{t('.btn.default_message')}"
            btn-processing-msg="#{t('.btn.processing_message')}"
            btn-sent-msg="#{t('.btn.sent_message')}"
            btn-error-msg="#{t('.btn.error_message')}"
          ]

app/views/gallery/index.html.slim
.wrapper.light-wrapper
  .container.inner.pt-70
    h1.heading.text-center
      =t '.title'
    h2.sub-heading2.text-center
      =t '.sub_title'
    .space50
    .tiles.grid
      .items.row.isotope.boxed.grid-view.text-center
        - GALLERY_CATEGORIES.each do |category|
          .item.grid-sizer.col-md-6.col-lg-4
            .box.bg-white.shadow.p-30
              figure.main.polaroid.overlay.overlay1
                a href="#{gallery_path(category.to_sym)}"
                  img src="/assets/art/#{category}/main.jpg" alt=""
                figcaption
                  h5.text-uppercase.from-top.mb-0 See Gallery
              h4.text-uppercase.mb-0
                =t ".categories.#{category}"

app/views/gallery/show.html.slim
.wrapper.light-wrapper
  .container.inner.pt-70.text-center
    h1.post-title
      =t ".categories.#{@category}"
    p
    .space30
    #cube-grid.cbp.light-gallery
      - Dir.glob("app/assets/images/art/#{@category}/*").each do |filepath|
        - new_filepath = filepath.split('app').last.split('images/').join
        .cbp-item
          figure.overlay.overlay3.rounded
            a href="#{new_filepath}"
              img src="#{new_filepath}" alt=""
.wrapper.light-wrapper
  .container.inner
    h2.section-title.text-center Other Galleries
    .cube-carousel.cbp.boxed.grid-view.text-center
      - GALLERY_CATEGORIES.each do |category|
        .cbp-item
          .box.bg-white.shadow.p-30
            figure.main.rounded.overlay.overlay1.mb-20
              a href="#{gallery_path(category.to_sym)}"
                img src="/assets/art/#{category}/main.jpg" alt=""
              figcaption
                h5.text-uppercase.from-top.mb-0 See Gallery
            h4.mb-0
              =t ".categories.#{category}"

app/views/home/show.html.slim
.rev_slider_wrapper.fullscreen-container
  #slider10.rev_slider.fullscreenbanner data-version="5.4.7"
    ul
      li data-transition="fade" data-thumb="/assets/art/slider-bg63.jpg"
        img src="/assets/art/slider-bg63.jpg" alt=""
      li data-transition="fade" data-thumb="/assets/art/slider-bg64.jpg"
        img src="/assets/art/slider-bg64.jpg" alt=""
      li data-transition="fade" data-thumb="/assets/art/slider-bg65.jpg"
        img src="/assets/art/slider-bg65.jpg" alt=""
      li data-transition="fade" data-thumb="/assets/art/slider-bg66.jpg"
        img src="/assets/art/slider-bg66.jpg" alt=""
      li data-transition="fade" data-thumb="/assets/art/slider-bg67.jpg"
        img src="/assets/art/slider-bg67.jpg" alt=""
      li data-transition="fade" data-thumb="/assets/art/slider-bg68.jpg"
        img src="/assets/art/slider-bg68.jpg" alt=""
      li data-transition="fade" data-thumb="/assets/art/slider-bg69.jpg"
        img src="/assets/art/slider-bg69.jpg" alt=""
      li data-transition="fade" data-thumb="/assets/art/slider-bg70.jpg"
        img src="/assets/art/slider-bg70.jpg" alt=""
    .tp-bannertimer.tp-bottom
.wrapper.light-wrapper
  .container.inner
    h1.heading.text-center Jonathan Missio Photography
    p.lead.larger.text-center
      | Hi! I’m Jonathan, a documentary wedding photographer currently working from and living in London.
      <br class="d-none d-lg-block" />
      | I absolutely love shooting weddings and couples because there are so much feeling to capture.
    .space30
    .tiles.grid
      .items.row.align-items-start.isotope.boxed.grid-view.text-center
        .item.grid-sizer.col-md-6
          .box.bg-pastel-default.p-30
            figure.main.mb-20.overlay.overlay1.rounded
              a href="javascript:void(0)"
                img src="/assets/art/about9.jpg" alt=""
              figcaption
                h5.text-uppercase.from-top.mb-0 Learn More
            h5.mb-0 About
        .item.grid-sizer.col-md-6
          .box.bg-pastel-default.p-30
            figure.main.mb-20.overlay.overlay1.rounded
              a href="javascript:void(0)"
                img src="/assets/art/f16.jpg" alt=""
              figcaption
                h5.text-uppercase.from-top.mb-0 Featured Shots
            h5.mb-0 Portfolio
        .item.grid-sizer.col-md-3
          .box.bg-pastel-default.p-30
            figure.main.mb-20.overlay.overlay1.rounded
              a href="javascript:void(0)"
                img src="/assets/art/f17.jpg" alt=""
              figcaption
                h5.text-uppercase.from-top.mb-0 Read Entries
            h5.mb-0 Journal
        .item.grid-sizer.col-md-3
          .box.bg-pastel-default.p-30
            figure.main.mb-20.overlay.overlay1.rounded
              a href="javascript:void(0)"
                img src="/assets/art/f18.jpg" alt=""
              figcaption
                h5.text-uppercase.from-top.mb-0 Get in Touch
            h5.mb-0 Contact
.wrapper.bg-pastel-default
  .container.inner
    h2.section-title.text-center Featured Shots
    p.lead.larger.text-center Photography is my passion and I love to turn ideas into beautiful things.
    .space30
    .flickity-carousel-container.fullscreen
      .flickity.flickity-carousel
        .item.mr-15
          img src="/assets/art/weddings/cw10.jpg" alt=""
        .item.mr-15
          img src="/assets/art/weddings/cw11.jpg" alt=""
        .item.mr-15
          img src="/assets/art/weddings/cw12.jpg" alt=""
        .item.mr-15
          img src="/assets/art/weddings/cw13.jpg" alt=""
        .item.mr-15
          img src="/assets/art/weddings/cw14.jpg" alt=""
        .item.mr-15
          img src="/assets/art/weddings/cw15.jpg" alt=""
        .item.mr-15
          img src="/assets/art/weddings/cw16.jpg" alt=""
        .item.mr-15
          img src="/assets/art/weddings/cw17.jpg" alt=""
        .item.mr-15
          img src="/assets/art/cw18.jpg" alt=""
      p.flickity-status
.wrapper.image-wrapper.bg-image.inverse-text data-image-src="/assets/art/bg16.jpg"
  .container.inner.pt-150.pb-150
    h1.heading.text-center
      | I take photographs with
      <br class="d-none d-lg-block" />
      | creativity, concept & passion
.wrapper.light-wrapper
  .container.inner
    h2.section-title.text-center My Specialties
    p.lead.larger.text-center I specialize in wedding photography, but I also love photographing couples and engagements.
    .space30
    .tiles
      .items.row.boxed.grid-view.text-center
        .item.col-md-4
          .box.bg-pastel-default.p-30
            figure.main.mb-20
              img src="/assets/art/si35.jpg" alt=""
            h5.mb-0 Wedding
        .item.col-md-4
          .box.bg-pastel-default.p-30
            figure.main.mb-20
              img src="/assets/art/si36.jpg" alt=""
            h5.mb-0 Engagement
        .item.col-md-4
          .box.bg-pastel-default.p-30
            figure.main.mb-20
              img src="/assets/art/si10.jpg" alt=""
            h5.mb-0 Couples
.wrapper.dark-wrapper.inverse-text
  .container.inner
    h2.section-title.text-center Behind the Scenes
    p.lead.larger.text-center
      | I would like to give you a unique photography and video experience, built to serve you best and
      <br class="d-none d-xl-block" />
      | capture your special moments for you and your families creatively and beautifully
    .space30
    .row
      .col-md-10.offset-md-1
        .player data-plyr-provider="vimeo" data-plyr-embed-id="94837904"
.wrapper.light-wrapper
  .container.inner
    h2.section-title.mb-40.text-center Notes from Love Bugs
    .row
      .col-md-10.offset-md-1
        .cube-slider.cbp-slider-edge.cbp
          .cbp-item.pl-60.pr-60.pb-10
            .row.d-flex
              .col-md-6.pr-35.pr-sm-15
                figure
                  img src="/assets/art/te1.jpg" alt=""
              .col-md-6.align-self-center
                blockquote.icon.icon-left
                  p Consectetur adipiscing elit. Duis mollis, est non commodo luctus gestas eget quam integer. Curabitur blandit tempus rutrum faucibus. Integer posuere erat a ante venenatis dapibus posuere velit aliquet.
                  footer.blockquote-footer Mildred & Austin
          .cbp-item.pl-60.pr-60.pb-10
            .row.d-flex
              .col-md-6.pr-35.pr-sm-15
                figure
                  img src="/assets/art/te2.jpg" alt=""
              .col-md-6.align-self-center
                blockquote.icon icon-left
                  p Consectetur adipiscing elit. Duis mollis, est non commodo luctus gestas eget quam integer. Curabitur blandit tempus rutrum faucibus. Integer posuere erat a ante venenatis dapibus posuere velit aliquet.
                  footer.blockquote-footer Mildred & Austin
          .cbp-item.pl-60.pr-60.pb-10
            .row.d-flex
              .col-md-6.pr-35.pr-sm-15
                figure
                  img src="/assets/art/te3.jpg" alt=""
              .col-md-6.align-self-center
                blockquote.icon.icon-left
                  p Consectetur adipiscing elit. Duis mollis, est non commodo luctus gestas eget quam integer. Curabitur blandit tempus rutrum faucibus. Integer posuere erat a ante venenatis dapibus posuere velit aliquet.
                  footer.blockquote-footer Mildred & Austin

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ichikawasatsuki2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    link rel="shortcut icon" href="/assets/favicon.png"
    title 市川五月OffitialWebsite
    = csrf_meta_tags
    = csp_meta_tag
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP" rel="stylesheet">
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .content-wrapper
      - if controller.controller_name.to_sym == :home
        = render 'common/home_header'
      - else
        = render 'common/header'
      = yield
      = render 'common/footer'
    = yield :vue_template
    = javascript_pack_tag    'application'
    = stylesheet_pack_tag    'application'

app/views/layouts/vue_application.html.slim
doctype html
html
  head
    meta http-equiv="content-language" content=I18n.locale
    script(
      name="config"
      data-env=Rails.env
      data-locale=I18n.locale
    )
    title 写真家 市川五月
    = csrf_meta_tags
    = csp_meta_tag

    link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP" rel="stylesheet"
    = javascript_include_tag 'missio_js'
    = stylesheet_pack_tag 'application'
  body
    #app
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

app/views/policy/show.html.slim
.wrapper.light-wrapper
  .container.inner.pt-70
    h2.section-title.mb-40.text-center
      =t '.title'
    .space20
    .box.bg-white.shadow
      .d-flex.flex-row.justify-content-center
        p.simple_format.policy-box
          =t '.policy'